
services:

  db:
      image: postgres:15
      restart: always
      environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: clientiq
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .  
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env  

  frontend:
    build: ./client-iq
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: